---
linters:
  disable-all: true
  enable:
    - bidichk
    - bodyclose
    - canonicalheader
    - contextcheck
    - copyloopvar
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - exhaustive
    - fatcontext
    - forcetypeassert
    - gocyclo
    - godot
    - gofmt
    - gosec
    - gosimple
    - govet
    - inamedparam
    - ineffassign
    - makezero
    - mirror
    - misspell
    - noctx
    - nosprintfhostport
    - predeclared
    - reassign
    - spancheck
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - typecheck
    - unconvert
    - unparam
    - usetesting
    - unused
    - whitespace
linters-settings:
  misspell:
    locale: US
  usestdlibvars:
    crypto-hash: true
    http-method: false
    sql-isolation-level: true
    time-layout: true
    tls-signature-scheme: true
